# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/chrisrichardmiles/',
                'doc_host': 'https://chrisrichardmiles.github.io',
                'git_url': 'https://github.com/chrisrichardmiles/chrisrichardmiles/tree/master/',
                'lib_path': 'chrisrichardmiles'},
  'syms': { 'chrisrichardmiles.core': {},
            'chrisrichardmiles.m5.daily_models': {},
            'chrisrichardmiles.m5.fe': {},
            'chrisrichardmiles.m5.metric': {},
            'chrisrichardmiles.m5.oos': {}}}