# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['dict_to_str']

# Cell
def dict_to_str(d: dict, sep: str = '::') -> str:
    return sep.join(
        [str(k) + sep + str(v) for k, v in sorted(d.items())])